[package]
name = "rust-scrobbler"
version = "0.2.0"
authors = ["Morelatto <morelatto@pm.me>"]
edition = "2018"

[dependencies]
rustfm-scrobble = "0.9.2"
id3 = "0.3.0"
config = "~0.1.0"
docopt = "1"
serde = { version = "1", features = ["derive"] }
glob = "0.3.0"